configure: Verify makespec before using it further
The chosen makespec may spit out errors for various reasons, which will
influence steps such as detecting pkg-config or the architecture test.

It's preferable to catch any issues with the makespec as early as
possible and exit configure before the errors propagate to tests.

Change-Id: Iecbf3217c36dea9f5e0677c58171b72cb6ce1e0b
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@digia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3719,6 +3719,20 @@ Prefix=..
 EOF
 
 #-------------------------------------------------------------------------------
+# Verify makespec
+#-------------------------------------------------------------------------------
+QMAKE_OUTPUT=`$outpath/bin/qmake -E -nocache -spec "$XQMAKESPEC" "CONFIG=" /dev/null 2>&1 >/dev/null`
+if [ $? != "0" ]; then
+    echo "Failed to process makespec for platform '$XPLATFORM'"
+    if [ "$OPT_VERBOSE" = "yes" ]; then
+        echo "$QMAKE_OUTPUT"
+    else
+        echo "Turn on verbose messaging (-v) to see the final report."
+    fi
+    exit 101
+fi
+
+#-------------------------------------------------------------------------------
 # write out device config before we run the test.
 #-------------------------------------------------------------------------------
 DEVICE_VARS_OUTFILE="$outpath/mkspecs/qdevice.pri"
