Fix configure script
Change-Id: I48482d399fcdef082c13858d21eb98c1cfdba0ae
Reviewed-by: Eskil Abrahamsen Blomfeldt <eskil.abrahamsen-blomfeldt@digia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -370,7 +370,6 @@ do
         XPLATFORM_ANDROID=yes
     fi
 done
-echo "XPLATFORM_ANDROID=$XPLATFORM_ANDROID"
 
 # detect the "echo without newline" style. usage: echo $ECHO_N "<string>$ECHO_C"
 if echo '\c' | grep '\c' >/dev/null; then
@@ -2819,15 +2818,28 @@ QMAKE_CONF_COMPILER=`getXQMakeConf QMAKE_CXX`
 TEST_COMPILER=$QMAKE_CONF_COMPILER
 
 if [ "$XPLATFORM_ANDROID" = "yes" ] ; then
-    # Repeat what mkspecs for android does. This is horrible, but I can't see a way around it given what getQMakeConf does.
-    NDK_TOOLCHAIN_PATH=$ANDROID_NDK_ROOT/toolchains/$ANDROID_NDK_TOOLCHAIN_PREFIX-$ANDROID_NDK_TOOLCHAIN_VERSION/prebuilt/$ANDROID_NDK_HOST
-    NDK_TOOLCHAIN_PREFIX=arm-linux-androideabi
-    # Replace all occourances of $$(EXAMPLE_VARIABLE) from qmake.conf with ${EXAMPLE_VARIABLE}
-    #  so we can eval it from shell script.
-    QMAKE_CONF_COMPILER=$NDK_TOOLCHAIN_PATH/$(echo "$QMAKE_CONF_COMPILER" | sed 's:\$\$(\([a-zA-Z_]*\)):\${\1}:g')
-
-    eval QMAKE_CONF_COMPILER=$QMAKE_CONF_COMPILER
-    TEST_COMPILER="$QMAKE_CONF_COMPILER --sysroot=$ANDROID_NDK_ROOT/platforms/android-5/arch-arm/"
+    ANDROID_NDK_TOOLS_PREFIX=
+    ANDROID_PLATFORM_ARCH=
+    case $CFG_DEFAULT_ANDROID_TARGET_ARCH in
+        armeabi*)
+            ANDROID_NDK_TOOLS_PREFIX=arm-linux-androideabi
+            ANDROID_PLATFORM_ARCH=arch-arm
+            ;;
+        x86)
+            ANDROID_NDK_TOOLS_PREFIX=x86
+            ANDROID_PLATFORM_ARCH=arch-x86
+            ;;
+        mips)
+            ANDROID_NDK_TOOLS_PREFIX=mipsel-linux-android
+            ANDROID_PLATFORM_ARCH=arch-mips
+            ;;
+        *)
+            echo "ERROR: Unknown android arch $CFG_DEFAULT_ANDROID_TARGET_ARCH"
+            exit 1
+            ;;
+    esac
+    QMAKE_CONF_COMPILER=$CFG_DEFAULT_ANDROID_NDK_ROOT/toolchains/$ANDROID_NDK_TOOLS_PREFIX-$CFG_DEFAULT_ANDROID_NDK_TOOLCHAIN_VERSION/prebuilt/$CFG_DEFAULT_ANDROID_NDK_HOST/bin/$ANDROID_NDK_TOOLS_PREFIX-g++
+    TEST_COMPILER="$QMAKE_CONF_COMPILER --sysroot=$CFG_DEFAULT_ANDROID_NDK_ROOT/platforms/$CFG_DEFAULT_ANDROID_PLATFORM/$ANDROID_PLATFORM_ARCH/"
 fi
 
 if [ "$XPLATFORM_SYMBIAN_SBSV2" = "no" ]; then
