Add Android specific options to configure script.
Fix compilation for Android x86 and MIPS platforms.

Task-number: QTBUG-29420
Change-Id: I2943983e99833f47a5896edb11f78517e502f65c
Reviewed-by: Eskil Abrahamsen Blomfeldt <eskil.abrahamsen-blomfeldt@digia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -965,6 +965,15 @@ CFG_SQL_oci=no
 CFG_SQL_db2=no
 
 CFG_SQL_AVAILABLE=
+
+# Android vars
+CFG_DEFAULT_ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT
+CFG_DEFAULT_ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT
+CFG_DEFAULT_ANDROID_PLATFORM=android-9
+CFG_DEFAULT_ANDROID_TARGET_ARCH=armeabi-v7a
+CFG_DEFAULT_ANDROID_NDK_TOOLCHAIN_VERSION=4.4.3
+CFG_DEFAULT_ANDROID_NDK_HOST=$ANDROID_NDK_HOST
+
 if [ -d "$relpath/src/plugins/sqldrivers" ]; then
   for a in "$relpath/src/plugins/sqldrivers/"*; do
      if [ -d "$a" ]; then
@@ -1026,7 +1035,7 @@ while [ "$#" -gt 0 ]; do
         VAL=no
         ;;
     #Qt style options that pass an argument
-    -prefix|-docdir|-headerdir|-plugindir|-importdir|-qmldir|-archdatadir|-datadir|-libdir|-bindir|-libexecdir|-translationdir|-sysconfdir|-examplesdir|-testsdir|-depths|-make|-nomake|-platform|-xplatform|-device|-device-option|-sdk|-arch|-host-arch|-mysql_config|-sysroot|-hostdatadir|-hostbindir|-qpa|-qconfig)
+    -prefix|-docdir|-headerdir|-plugindir|-importdir|-qmldir|-archdatadir|-datadir|-libdir|-bindir|-libexecdir|-translationdir|-sysconfdir|-examplesdir|-testsdir|-depths|-make|-nomake|-platform|-xplatform|-device|-device-option|-sdk|-arch|-host-arch|-mysql_config|-sysroot|-hostdatadir|-hostbindir|-qpa|-qconfig|-android-sdk|-android-ndk|-android-ndk-platform|-android-ndk-host|-android-arch|-android-toolchain-version)
         VAR=`echo $1 | sed "s,^-\(.*\),\1,"`
         shift
         VAL="$1"
@@ -2175,6 +2184,44 @@ while [ "$#" -gt 0 ]; do
             else
                 UNKNOWN_OPT=yes
             fi
+    android-sdk)
+        if [ "$XPLATFORM_ANDROID" = "yes" ]; then
+            CFG_DEFAULT_ANDROID_SDK_ROOT="$VAL"
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
+    android-ndk)
+        if [ "$XPLATFORM_ANDROID" = "yes" ]; then
+            CFG_DEFAULT_ANDROID_NDK_ROOT="$VAL"
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
+    android-ndk-platform)
+        if [ "$XPLATFORM_ANDROID" = "yes" ]; then
+            CFG_DEFAULT_ANDROID_PLATFORM="$VAL"
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
+    android-ndk-host)
+        if [ "$XPLATFORM_ANDROID" = "yes" ]; then
+            CFG_DEFAULT_ANDROID_NDK_HOST="$VAL"
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
+    android-arch)
+        if [ "$XPLATFORM_ANDROID" = "yes" ]; then
+            CFG_DEFAULT_ANDROID_TARGET_ARCH="$VAL"
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
+    android-toolchain-version)
+        if [ "$XPLATFORM_ANDROID" = "yes" ]; then
+            CFG_DEFAULT_ANDROID_NDK_TOOLCHAIN_VERSION="$VAL"
         else
             UNKNOWN_OPT=yes
         fi
@@ -2574,6 +2621,65 @@ case `basename "$XPLATFORM"` in win32-g++*) XPLATFORM_MINGW=yes;; esac
 case "$XPLATFORM" in *-maemo*) XPLATFORM_MAEMO=yes;; esac
 case "$XPLATFORM" in *qnx-*|*blackberry-*) XPLATFORM_QNX=yes;; esac
 case "$XPLATFORM" in *android*) XPLATFORM_ANDROID=yes;; esac
+
+if [ "$XPLATFORM_ANDROID" = "yes" ]; then
+    if [ -z "$CFG_DEFAULT_ANDROID_NDK_ROOT" ]; then
+        echo
+        echo "Can not find Android NDK. Please use -android-ndk option to specify one"
+        exit 1
+    fi
+    if [ -z "$CFG_DEFAULT_ANDROID_SDK_ROOT" ]; then
+        echo
+        echo "Can not find Android SDK. Please use -android-sdk option to specify one"
+        exit 1
+    fi
+
+    QT_QPA_DEFAULT_PLATFORM="android"
+    CFG_LARGEFILE="no"
+
+    cp -f $CFG_DEFAULT_ANDROID_NDK_ROOT/sources/cxx-stl/gnu-libstdc++/$CFG_DEFAULT_ANDROID_NDK_TOOLCHAIN_VERSION/libs/$CFG_DEFAULT_ANDROID_TARGET_ARCH/libgnustl_shared.so $outpath/lib
+
+    if [ -z "$CFG_DEFAULT_ANDROID_NDK_HOST" ]; then
+        case $PLATFORM in
+        linux-*-64)
+            if [ -d "$CFG_DEFAULT_ANDROID_NDK_ROOT/arm-linux-androideabi-$CFG_DEFAULT_ANDROID_NDK_TOOLCHAIN_VERSION/linux-x86_64" ]; then
+                CFG_DEFAULT_ANDROID_NDK_HOST=linux-x86_64
+            else
+                CFG_DEFAULT_ANDROID_NDK_HOST=linux-x86
+            fi
+            ;;
+        linux-*)
+            CFG_DEFAULT_ANDROID_NDK_HOST=linux-x86
+            ;;
+        macx-*)
+            CFG_DEFAULT_ANDROID_NDK_HOST=darwin-x86
+            if [ ! -z "$NATIVE_64_ARCH" ] && [ -d "$CFG_DEFAULT_ANDROID_NDK_ROOT/arm-linux-androideabi-$CFG_DEFAULT_ANDROID_NDK_TOOLCHAIN_VERSION/darwin-x86_64" ]; then
+                CFG_DEFAULT_ANDROID_NDK_HOST=darwin-x86_64
+            fi
+            ;;
+        win32-*)
+            CFG_DEFAULT_ANDROID_NDK_HOST=windows
+            if [ ! -z "$NATIVE_64_ARCH" ] && [ -d "$CFG_DEFAULT_ANDROID_NDK_ROOT/arm-linux-androideabi-$CFG_DEFAULT_ANDROID_NDK_TOOLCHAIN_VERSION/windows-x86_64" ]; then
+                CFG_DEFAULT_ANDROID_NDK_HOST=windows-x86_64
+            fi
+            ;;
+        esac
+        if [ -z "$CFG_DEFAULT_ANDROID_NDK_HOST" ] || [ -d "$CFG_DEFAULT_ANDROID_NDK_ROOT/arm-linux-androideabi-$CFG_DEFAULT_ANDROID_NDK_TOOLCHAIN_VERSION/$CFG_DEFAULT_ANDROID_NDK_HOST" ]; then
+            echo
+            echo "Can not detect the android host, please use -android-ndk-host option to specify one"
+            exit 1
+        fi
+    else
+        exit 0
+    fi
+
+    DeviceVar set DEFAULT_ANDROID_SDK_ROOT "$CFG_DEFAULT_ANDROID_SDK_ROOT"
+    DeviceVar set DEFAULT_ANDROID_NDK_ROOT "$CFG_DEFAULT_ANDROID_NDK_ROOT"
+    DeviceVar set DEFAULT_ANDROID_PLATFORM "$CFG_DEFAULT_ANDROID_PLATFORM"
+    DeviceVar set DEFAULT_ANDROID_NDK_HOST "$CFG_DEFAULT_ANDROID_NDK_HOST"
+    DeviceVar set DEFAULT_ANDROID_TARGET_ARCH "$CFG_DEFAULT_ANDROID_TARGET_ARCH"
+    DeviceVar set DEFAULT_ANDROID_NDK_TOOLCHAIN_VERSION "$CFG_DEFAULT_ANDROID_NDK_TOOLCHAIN_VERSION"
+fi
 
 if [ -d "$PLATFORM" ]; then
   QMAKESPEC="$PLATFORM"
@@ -3382,6 +3488,7 @@ Additional options:
 
  $GBN  -no-glib ........... Do not compile Glib support.
  $GBY  -glib .............. Compile Glib support.
+
 EOF
 
 if [ "$XPLATFORM_MAEMO" = "yes" ]; then
@@ -3424,6 +3531,32 @@ Qt/Mac only:
                          QT_ENABLE_HARFBUZZ environment variable.
 
 EOF
+fi
+
+if [ "$XPLATFORM_ANDROID" = "yes" ]; then
+    cat << EOF
+
+Android options:
+    -android-sdk path .............. The Android SDK root path.
+                                     (default $CFG_DEFAULT_ANDROID_SDK_ROOT)
+
+    -android-ndk path .............. The Android NDK root path.
+                                     (default $CFG_DEFAULT_ANDROID_NDK_ROOT)
+
+    -android-ndk-platform .......... Sets the android platform
+                                     (default $CFG_DEFAULT_ANDROID_PLATFORM)
+
+    -android-ndk-host .............. Sets the android NDK host (linux-x86, linux-x86_64, etc.)
+                                     (default $CFG_DEFAULT_ANDROID_NDK_HOST)
+
+    -android-arch .................. Sets the android architecture (armeabi, armeabi-v7a, x86, mips)
+                                     (default $CFG_DEFAULT_ANDROID_TARGET_ARCH)
+
+    -android-toolchain-version ..... Sets the android toolchain version
+                                     (default $CFG_DEFAULT_ANDROID_NDK_TOOLCHAIN_VERSION)
+
+EOF
+
 fi
 
    [ "x$ERROR" = "xyes" ] && exit 1
@@ -5126,7 +5259,7 @@ if [ "$BUILD_ON_MAC" = "yes" ]; then
     fi
 fi
 
-if [ "$BUILD_ON_MAC" = "no" ] && [ "$XPLATFORM_MINGW" = "no" ] && [ "$XPLATFORM_QNX" = "no" ]; then
+if [ "$BUILD_ON_MAC" = "no" ] && [ "$XPLATFORM_MINGW" = "no" ] && [ "$XPLATFORM_QNX" = "no" ] && [ "$XPLATFORM_ANDROID" = "no" ]; then
     if [ "$CFG_XCB" = "no" ] && [ "$CFG_EGLFS" = "no" ] && [ "$CFG_DIRECTFB" = "no" ] && [ "$CFG_LINUXFB" = "no" ] && [ "$CFG_KMS" = "no" ]; then
         if [ "$QPA_PLATFORM_GUARD" = "yes" ] &&
             ( [ "$ORIG_CFG_XCB" = "auto" ] || [ "$ORIG_CFG_EGLFS" = "auto" ] || [ "$ORIG_CFG_DIRECTFB" = "auto" ] || [ "$ORIG_CFG_LINUXFB" = "auto" ] || [ "$ORIG_CFG_KMS" = "auto" ] ); then
@@ -5275,24 +5408,20 @@ fi
 
 # detect OpenSSL
 if [ "$CFG_OPENSSL" != "no" ]; then
-    if [ "$XPLATFORM_ANDROID" != "yes" ]; then
-        if compileTest unix/openssl "OpenSSL"; then
-            if [ "$CFG_OPENSSL" = "auto" ]; then
-                CFG_OPENSSL=yes
-            fi
-        else
-            if ( [ "$CFG_OPENSSL" = "yes" ] || [ "$CFG_OPENSSL" = "linked" ] ) && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]  && [ "$XPLATFORM_ANDROID" = "no" ]; then
-                echo "OpenSSL support cannot be enabled due to functionality tests!"
-                echo " Turn on verbose messaging (-v) to $0 to see the final report."
-                echo " If you believe this message is in error you may use the continue"
-                echo " switch (-continue) to $0 to continue."
-                exit 101
-            else
-                CFG_OPENSSL=no
-            fi
+    if compileTest unix/openssl "OpenSSL"; then
+        if [ "$CFG_OPENSSL" = "auto" ]; then
+            CFG_OPENSSL=yes
         fi
     else
-        CFG_OPENSSL=yes
+        if ( [ "$CFG_OPENSSL" = "yes" ] || [ "$CFG_OPENSSL" = "linked" ] ) && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]  && [ "$XPLATFORM_ANDROID" = "no" ]; then
+            echo "OpenSSL support cannot be enabled due to functionality tests!"
+            echo " Turn on verbose messaging (-v) to $0 to see the final report."
+            echo " If you believe this message is in error you may use the continue"
+            echo " switch (-continue) to $0 to continue."
+            exit 101
+        else
+            CFG_OPENSSL=no
+        fi
     fi
 fi
 
